name: cwfm

on:
  push:
    branches:
      - main
      - develope

jobs:
  main-test:
    name: Ubuntu
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run profile
        run: docker-compose --profile prod up -d
      - name: Running phpunit
        run: ./vendor/bin/phpunit --verbose tests
      - name: Docker login
        run: docker login -u goalldex -p ${{ secrets.DOCKER_TOKEN }}
      - name: To Docker Hub
        run: docker push goalldex/cwfm:latest