name: cwfm

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
      working-directory: ./CWFM
      run: composer install --prefer-dist
      - name: Run Tests
      working-direcotry: ./CWFM
      run: composer run-phpunit
      - run: docker build --target webserver -t ./CWFM/docker-compose
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
